/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef, useState } from "react";
import { Sphere, SpotLight, useGLTF, useHelper } from "@react-three/drei";
import { Bloom } from "@react-three/postprocessing";
import { useControls } from "leva";
import { useFrame } from "@react-three/fiber";
import { Color, DirectionalLightHelper, PointLightHelper } from "three";

export function BulbLight(props) {
  const { nodes, materials } = useGLTF("assets/models/bulb-light.glb");
  const [triggerLight, setTriggerLight] = useState(false);

  const lightRef = useRef();
  const pointLight = useRef();

  useHelper(lightRef, DirectionalLightHelper, 1);
  useHelper(pointLight, PointLightHelper, 1);

  const { activeLight, position } = useControls("Bulb Light", {
    activeLight: {
      value: false,
      onChange: (value) => {
        setTriggerLight(value);
      },
    },
    position: [0, 3.5, 2],
  });

  useFrame((state, delta) => {
    if (triggerLight && lightRef.current.intensity < 3) {
      lightRef.current.intensity += delta / 2;
      console.log(lightRef.current.intensity);
    }

    if (triggerLight && lightRef.current.distance < 12) {
      lightRef.current.distance += delta;
      console.log(lightRef.current.distance);
    }
  });

  return (
    <group {...props} dispose={null}>
      <Bloom />

      <SpotLight
        ref={lightRef}
        intensity={0}
        attenuation={10}
        distance={2}
        angle={3}
        // target={position}
        penumbra={1}
        // position-y={5}
        // position-z={-5}
      />
      <pointLight ref={pointLight} position={[0, 3, -1]} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        position={[0.5, 3.2, -2.3]}
        rotation={[-2.9, 0, 3.1]}
      >
        <meshStandardMaterial
          color={[1.5, 1, 4]}
          toneMapped={false}
          emissiveIntensity={2}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={materials["Material.002"]}
        position={[0.5, 3.3, -2.7]}
        rotation={[-2.9, 0, 3.1]}
        scale={1.1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001.geometry}
        material={materials["Material.005"]}
        position={[0.5, 3.2, -2.4]}
        rotation={[-1.3, 0, 3.1]}
        scale={0.1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials["Material.006"]}
        position={[0.4, 3.1, -2]}
        rotation={[-1.3, 0, 3]}
        scale={0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials["Material.006"]}
        position={[0.5, 3.1, -2]}
        rotation={[-1.3, 0, -3.1]}
        scale={0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={nodes.Cube002.material}
        position={[0.6, 3.1, -2]}
        rotation={[-1.3, 0, -1.2]}
        scale={0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={nodes.Cube003.material}
        position={[0.6, 3.1, -1.9]}
        rotation={[-1.3, 0, -1.4]}
        scale={0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={nodes.Cube004.material}
        position={[0.6, 3.1, -2.1]}
        rotation={[-1.3, 0, -1.3]}
        scale={0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={nodes.Cube005.material}
        position={[0.5, 3.2, -2.1]}
        rotation={[-1.3, 0, -1.4]}
        scale={0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={nodes.Cube006.material}
        position={[0.5, 3.2, -2.2]}
        rotation={[-1.3, 0, -1.4]}
        scale={0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={nodes.Cube007.material}
        position={[0.5, 3.2, -2.3]}
        rotation={[-1.3, 0, -1.4]}
        scale={0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={nodes.Cube008.material}
        position={[0.4, 3.1, -1.9]}
        rotation={[-1.4, 0, -1.7]}
        scale={0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={nodes.Cube010.material}
        position={[0.4, 3.2, -2.2]}
        rotation={[-1.4, 0, -1.7]}
        scale={0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube011.geometry}
        material={nodes.Cube011.material}
        position={[0.4, 3.2, -2.2]}
        rotation={[-1.4, 0, -1.7]}
        scale={0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube012.geometry}
        material={nodes.Cube012.material}
        position={[0.4, 3.2, -2.3]}
        rotation={[-1.4, 0, -2.1]}
        scale={0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube013.geometry}
        material={nodes.Cube013.material}
        position={[0.4, 3.1, -2]}
        rotation={[-1.3, 0, -1.3]}
        scale={0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube014.geometry}
        material={materials["Material.006"]}
        position={[0.4, 3.1, -2]}
        rotation={[-1.3, 0, -3.1]}
        scale={0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube015.geometry}
        material={materials["Material.006"]}
        position={[0.4, 3.1, -2]}
        rotation={[-1.3, 0, -3.1]}
        scale={0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane006.geometry}
        material={materials["Material.005"]}
        position={[0.5, 3.3, -2.7]}
        rotation={[-2.9, 0, 0.4]}
        scale={1.1}
      />
    </group>
  );
}

useGLTF.preload("assets/models/bulb-light.glb");
